spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: hazelcast-sample
  datasource:
    url: jdbc:h2:mem:netz-lmsx;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false

cache:
  hostnames: 192.168.56.20:5701#
  username: dev
  password: dev-pass

